name: 'Direnv'
description: 'Install, allow, and load direnv'
inputs:
  default-branch:
    required: false
    description: The default branch to restore the direnv cache from
    default: main
outputs: {}
runs:
  using: "composite"
  steps:
    - uses: cachix/install-nix-action@v18
    - name: Cache direnv
      id: cache-direnv
      uses: actions/cache@v3
      with:
        key: direnv-${{ runner.os }}-${{ github.ref_name }}
        restore-keys: |
          direnv-${{ runner.os }}-${{ inputs.default-branch }}
          direnv-${{ runner.os }}-
        path: /tmp/direnv-out
    - shell: bash
      name: Import direnv cache
      run: |
        if [ -f /tmp/direnv-out ]; then
          echo "cache hit, importing direnv store paths"
          nix-store --import < /tmp/direnv-out
        else
          echo "cache miss, skipping import"
        fi
    - run: GITHUB_TOKEN=${{ github.token }} bash ${{ github.action_path }}/install.sh
      shell: bash
    - run: direnv allow
      shell: bash
    - run: direnv export gha >> "$GITHUB_ENV"
      shell: bash
    - shell: bash
      name: Export direnv
      run: nix-store --export $(nix-store -qR $(find .direnv -type l)) > /tmp/direnv-out
