name: 'Direnv'
description: 'Install, allow, and load direnv'
inputs: {}
outputs: {}
runs:
  using: "composite"
  steps:
    - uses: cachix/install-nix-action@v18
    - run: GITHUB_TOKEN=${{ github.token }} bash ${{ github.action_path }}/install.sh
      shell: bash
    - run: direnv allow
      shell: bash
    - run: direnv export gha >> "$GITHUB_ENV"
      shell: bash
