name: 'Direnv'
description: 'Install, allow, and load direnv'
inputs:
  github-token:
    description: 'The secrets.GITHUB_TOKEN for this workflow'
    required: true
    default: ''
outputs: {}
runs:
  using: "composite"
  steps:
    - run: |
       curl --retry 5 --retry-all-errors -sfL https://direnv.net/install.sh \
         | sed 's/curl/curl --retry 5 --retry-all-errors --header "authorization: Bearer ${{ inputs.github-token }}"/g' \
         | bash
      shell: bash
    - run: direnv allow
      shell: bash
    - run: direnv export gha >> "$GITHUB_ENV"
      shell: bash
