name: 'Direnv'
description: 'Install, allow, and load direnv'
inputs: {}
outputs: {}
runs:
  using: "composite"
  steps:
    - uses: cachix/install-nix-action@v18
    - name: Cache direnv
      id: cache-direnv
      uses: actions/cache@v3
      with:
        key: direnv
        path: /tmp/direnv-out
    - shell: bash
      name: Import direnv cache
      if: steps.cache-direnv.outputs.cache-hit == 'true'
      run: nix-store --import < /tmp/direnv-out
    - run: GITHUB_TOKEN=${{ github.token }} bash ${{ github.action_path }}/install.sh
      shell: bash
    - run: direnv allow
      shell: bash
    - run: direnv export gha >> "$GITHUB_ENV"
      shell: bash
    - shell: bash
      name: Export direnv
      run: nix-store --export $(nix-store -qR $(find .direnv -maxdepth 1 -type l)) > /tmp/direnv-out
