on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: Continuous integration

jobs:
  action:
    name: Run Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./